### ISSUE TITLE
Nested describes are ommited

### ISSUE THREAD

**Issue by tiriana** [webdriverio/wdio-spec-reporter#27]
For following suites:

```
describe("suite 1", function () {
        it("outside", function () {
            expect(true).to.be.true;
        });
        describe("subsuite", function () {
            it("inside", function () {
                expect(true).to.be.true;
            });
        });
    });

    describe("suite 2", function () {
        it("outside", function () {
            expect(true).to.be.true;
        });
        describe("subsuite", function () {
            it("inside", function () {
                expect(true).to.be.true;
            });
        });
    });
```

I get this output:

```
[chrome #0-0] suite 1
[chrome #0-0]   ✓ outside
[chrome #0-0]
[chrome #0-0] subsuite
[chrome #0-0]   ✓ inside
[chrome #0-0]
[chrome #0-0] suite 2
[chrome #0-0]   ✓ outside

[chrome #0-0] 4 passing (5s)
```

"suite 2 -> subsuite -> inside" is missing. It is ran (judging from number of tests passing), but is not displayed.

**Comment by christian-bromann** [comment]
@tiriana what version of wdio-spec-reporter are you using?

**Comment by tiriana** [comment]
@christian-bromann I used 0.1.0 (the output I attached comes from this version). But this also occurs in 0.0.3, only indentions are a little different.

**Comment by christian-bromann** [comment]
Please update to `0.1.0` where it should be fixed

**Comment by tiriana** [comment]
It occurs on both 0.1.0 and 0.0.3. It says so in my previous comment.

**Comment by christian-bromann** [comment]
@tiriana I just ran your spec with latest WebdriverIO and spec reporter and got
```
------------------------------------------------------------------
[phantomjs #0-0] Session ID: f014f6e6-54b8-40f5-a15d-9e5b04816924
[phantomjs #0-0] Spec: /Users/christianbromann/Sites/Webprojekte/webdriverjs/issues/spec27/test.js
[phantomjs #0-0] Running: phantomjs
[phantomjs #0-0]
[phantomjs #0-0] suite 1
[phantomjs #0-0]   ✓ outside
[phantomjs #0-0]
[phantomjs #0-0]     subsuite
[phantomjs #0-0]       ✓ inside
[phantomjs #0-0]
[phantomjs #0-0] suite 2
[phantomjs #0-0]   ✓ outside
[phantomjs #0-0]
[phantomjs #0-0]     subsuite
[phantomjs #0-0]       ✓ inside
[phantomjs #0-0]
[phantomjs #0-0]
[phantomjs #0-0] 4 passing (2s)
[phantomjs #0-0]
```

**Comment by tiriana** [comment]
:/ that's strange... Ok, I'll try to check it again with latest reporter.
Maybe the issue is somewhere else.

**Comment by tiriana** [comment]
@christian-bromann 
I tried on "wdio-spec-reporter@0.1.0" and It's still the same form me - I don's see ```suite 2 -> subsuite -> inside```
I failed to run this on phantomjs service.  Can you send me your wdio config on which phantomjs is working fine? Or try to run it on chrome? 
Not sure if browser has anything to do with it, but it's the only thing that differs in our setups now.

**Comment by christian-bromann** [comment]
> Not sure if browser has anything to do with it

It has not. Here is what you do:

- create a new directory
- download webdriverio
- run `./node_modules/.bin/wdio`
- go through the setup and select spec reporter
- create a test file like above
- run it

**Comment by tiriana** [comment]
It works fine with fresh setup... There must be something else wrong with our setup.

If you have any clues/hints/ideas what can I check next - please let me know. It will speed up my investigation.

Thank you so much for support.

**Comment by christian-bromann** [comment]
@tiriana remove your node_modules directory and install all dependencies again
